version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - ls

      - aws s3api put-object --bucket "codebuild-us-west-2-624086151665-output-bucket" --key "template.yml" --body template.yml
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - cp template.yml target
artifacts:
  files:
    - target/*
